### PR TITLE
Feature/local images

### PR DESCRIPTION
**Pull request by adamgruber**
Alternate approach to #5 
- support local image paths
- style tweaks

### CODE REVIEW

**Comment by AlehVasilyeu** [comment]
Checked it today, works fine with local images, thanks a lot. :) When will you release fix?

**Comment by adamgruber** [comment]
Hoping to push out a release today if I can. It's tough trying to balance real work with side projects. 😉

**Comment by adamgruber** [comment]
@AlehVasilyeu 1.0.4 released

**Comment by AlehVasilyeu** [comment]
@adamgruber Super cool, thanks a lot.

**Comment by wimdeblauwe** [comment]
Is there documentation on how to use this ?

**Comment by codemonkeynumber24** [comment]
Still curious if there is any documentation on how to use the local images

**Pull request merged**
