### PR TITLE
No react deps

### LINKED ISSUE #143: Remove react and react-dom dependencies
Currently `react` and `react-dom` are only used to create the initial HTML string. This can be done using only template literals thus removing the need for `react` to be installed as a dependency.

### PR DESCRIPTION
**Pull request by adamgruber**
Converts <MainHTML> component into a function that uses template literals instead of JSX.
End result is that the package will no longer depend on `react` or `react-dom`. 

Closes #143

### CODE REVIEW

**Comment by Hypercubed** [comment]
Not arguing with this change... but it does break npx.

**Comment by adamgruber** [comment]
how so?

**Comment by Hypercubed** [comment]
Seeing this on CI... 

image

I think the solution is to not use npx...

**Comment by adamgruber** [comment]
Will `npx` use the latest version? With the changes I've just made, react should not be required at all.

**Comment by Hypercubed** [comment]
Hmmm... It should... CI started failing a few hours ago.  We're still not able to repo locally.  Some CI quark?

**Comment by adamgruber** [comment]
All works as expected in the testing I've done. Ensure that you're installing the lastest `mochawesome` in the CI environment.

**Comment by Hypercubed** [comment]
Yeah... mochawesome is an older version.  npx is using the latest mochawesome-report-generator.   Looks like our end... sorry for the false alarm!

**Pull request merged**
