### PR TITLE
Add base64 image support

### PR DESCRIPTION
**Pull request by gidztech**
https://github.com/adamgruber/mochawesome/issues/171

### CODE REVIEW

**Comment by gidztech** [comment]
Cool thanks. Looking forward to having my VRT screenshots in test reports once you hit the magic release button.

**Comment by adamgruber** [comment]
@gidztech 2.3.0 released. Thanks again 👍

**Comment by gidztech** [comment]
@adamgruber It looks like something has gone wrong with the release. I'm getting `TypeError: marge.getBaseConfig is not a function`.

**Comment by adamgruber** [comment]
@gidztech Sorry for the botched release. I published 2.3.1 which should be ok. There was some lint and I forgot to run build before publishing. That'll teach me to release stuff after a long day.

**Comment by gidztech** [comment]
@adamgruber No problem. Working great now 👍

**Pull request merged**
